version: "3.9"

services:
  forms_rest:
    container_name: forms_rest
    build: ./forms_rest
    ports:
      - "8000:8000"
    environment:
      - PG_USER=postgres
      - PG_PASSWORD=postgres
      - PG_DB=postgres
      - PG_PORT=5432
      - PG_HOST=db
      - SECRET_KEY=django-insecure-7m3qn+sjc7)m&@3vg$l5iu=+oa1fw(ffb11%+58tdq+r6dki*)
      - DEBUG=true
    volumes:
      - ./forms_rest:/usr/src/app
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:12
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"