# Generated by Django 5.0.3 on 2024-04-03 17:56

import api.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CheckboxQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('choices_list_string', models.CharField(max_length=300, validators=[api.models.MultipleChoicesQuestion.validate_list])),
                ('correct_answers_string', models.CharField(max_length=300, validators=[api.models.MultipleChoicesQuestion.validate_list])),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkboxquestions', to='api.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('choices_list_string', models.CharField(max_length=300, validators=[api.models.MultipleChoicesQuestion.validate_list])),
                ('correct_answer', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radioquestions', to='api.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=1)),
                ('correct_answer', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textquestions', to='api.form')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
    ]
