# Generated by Django 5.0.3 on 2024-03-30 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_form_body_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('TX', 'Text'), ('RD', 'Radio'), ('CH', 'CHECKBOX')], default='text', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.IntegerField(default=1),
        ),
    ]
