# Generated by Django 5.0.3 on 2024-03-31 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_question_question_type_alter_question_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckboxQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('choices_list', models.CharField(max_length=300)),
                ('correct_answers', models.CharField(max_length=300)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkboxquestions', to='api.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RadioQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('choices_list', models.CharField(max_length=300)),
                ('correct_answer', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radioquestions', to='api.form')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=1)),
                ('correct_answer', models.CharField(max_length=100)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='textquestions', to='api.form')),
            ],
            options={
                'ordering': ['order'],
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
