# Generated by Django 5.0.3 on 2024-03-31 20:39

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_choices_list_checkboxquestion_choices_list_string_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkboxquestion',
            name='correct_answers',
        ),
        migrations.AddField(
            model_name='checkboxquestion',
            name='correct_answers_string',
            field=models.CharField(default='["ginger", "nigger"]', max_length=300, validators=[api.models.MultipleChoicesQuestion.validate_list]),
            preserve_default=False,
        ),
    ]
