# Generated by Django 5.0.3 on 2024-04-01 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_checkboxquestion_correct_answers_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='name',
            new_name='title',
        ),
    ]
